### ISSUE TITLE
Creazione EMAC

### ISSUE THREAD

**Issue by Gianlo98** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#1]
Bisogna creare una classe EMAC nel package `com.unimib.smarthome.emac` che abbia le seguenti caratteristiche:
- [x] Implementi l'interfaccia observer in modo da essere notificata da `EntityManager` per ogni cambiamento di stato. Un cambiamento di stato è rappresentato dai parametri (int entityID, String newState)
- [x] Implementi un metodo ` registryAutomation(Request r)` per registrare tutte le automazioni di cui si dovrà occupare l'EMAC. (ti consiglio di usare una mappa `<Integer, List<Request>>` così da associare ad ogni id, una **lista di richieste il cui ID sia presente in una delle condizioni** (proprietà `if` di Request)
- [x] Non appena rileva un cambiamento di stato (punto 1), prende tutte le richieste la cui entità appartiene nelle condizioni (punto 2) e ne filtra le sole valide (cioè quelle le cui condizioni sono tutte verificare; per verificare una condizione usare `entityManager.getState(entityID)`
- [x] Esegue tutte le richieste valide in ordine di priorità (retainLevel) e retain flag attivo. Per eseguire una richiesta basta invocare il metodo `executeRequest()` di una richiesta

**Comment by D-Mex** [comment]
> Un cambiamento di stato è rappresentato dai parametri (int entityID, String newState)

Il valore con cui risolvo newState da dove proviene? A quale attributo di entity corrisponde?

**Comment by Gianlo98** [comment]
Il cambiamento di stato non è altro che una notifica (observer) da parte di `EntityManager`.

![immagine](https://user-images.githubusercontent.com/7064130/73120780-9103fa00-3f72-11ea-9420-74b4b6673c1a.png)

Quando `EntityManager` chiama il metodo `update()` dell'EMAC gli passa come parametri (int entityID, String newState) (Queste sono le notifiche dell'observer)

I parametri (int entityID, String newState) sono puramente teorici, l'implementazione è a tua scelta; anzichè 2 parametri potresti passare un oggetto `EntityStatus` contenente questi 2 paramentri. 
L'importante è che EntityManager con observer notifichi l'EMAC del cambiamento di stato di un'entità, il come vuoi implementarlo è una tua libera scelta.

**Comment by ChrisTasca1997** [comment]
Appena viene implementato il metodo registryAutomation(Request r) potete avvisarmi?
Mi serve per testare la classe systemInit.java, grazie.

**Comment by D-Mex** [comment]
`public void filter(Entity entity) {
		//tutte le richieste relative ad entity
		List<Request> requests = idToRequests.get(entity.getId());
		List<Request> validRequests = new ArrayList<>();
		//filtra le sole valide
		for (Request r : requests) {
			boolean verified = true;
			for (int i = 0; i < r.getCondition().length; i++) {
				if (!r.getCondition()[i].getState().equals(EntityManager.getInstance().getEntityState(entity.getId()))) {
					verified = false;
				}
			}
			if (verified) {
				validRequests.add(r);
			}
		}
	}`

Può essere una soluzione efficace per il punto 3?

**Comment by D-Mex** [comment]
`public void filter(Entity entity) {
		//tutte le richieste relative ad entity
		List<Request> requests = idToRequests.get(entity.getId());
		List<Request> validRequests = new ArrayList<>();
		//filtra le sole valide
		for (Request r : requests) {
			boolean verified = true;
			for (int i = 0; i < r.getCondition().length; i++) {
				if (!r.getCondition()[i].getState().equals(EntityManager.getInstance().getEntityState(entity.getId()))) {
					verified = false;
				}
			}
			if (verified) {
				validRequests.add(r);
			}
		}
	}`

**Comment by D-Mex** [comment]
public void filter(Entity entity) {
		//tutte le richieste relative ad entity
		List<Request> requests = idToRequests.get(entity.getId());
		List<Request> validRequests = new ArrayList<>();
		//filtra le sole valide
		for (Request r : requests) {
			boolean verified = true;
			for (int i = 0; i < r.getCondition().length; i++) {
				if (!r.getCondition()[i].getState().equals(EntityManager.getInstance().getEntityState(entity.getId()))) {
					verified = false;
				}
			}
			if (verified) {
				validRequests.add(r);
			}
		}
	}

**Comment by D-Mex** [comment]
> Appena viene implementato il metodo registryAutomation(Request r) potete avvisarmi?
> Mi serve per testare la classe systemInit.java, grazie.

Pronti!

**Comment by D-Mex** [comment]
Nella task 4, una volta eseguita la Request mi serve tenerne traccia nell'Emac o la posso "buttare via"?

**Comment by ChrisTasca1997** [comment]
> Nella task 4, una volta eseguita la Request mi serve tenerne traccia nell'Emac o la posso "buttare via"?

Le richieste eseguite vengono "registrate" nel conflictpool, che è una classe del package SEC, quindi emac non deve tenerne traccia, lui deve solo controllare le condizioni quando c'è un cambiamento di stato, ed eseguire la richiesta in caso le condizioni siano verificate, ma poi può "eliminare" dalla sua base di conoscenza quest'ultima.
