### ISSUE TITLE
Creazione Entities tramite SystemInit

### ISSUE THREAD

**Issue by ChrisTasca1997** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#11]
Nei vari test per il funzionamento di SystemInit ma più precisamente di CLIService, ho notato che inizialmente lo stato dell'entità è settata su null, questo perché nel nostro file Json non facciamo settare lo stato iniziale dell'entità, posso capire per i sensori, dove lo stato non può essere cambiato, ma nel caso della luce e dei dispositivi programmabili, non dovremmo impostargli uno stato iniziale? Nel caso ditemelo, che lo implemento.

**Comment by Gianlo98** [comment]
Certo, lo stato iniziale dipende dal tipo di dispositivo che stai andando a creare estendendo la classe `Entity `perciò propongo di mettere come stato inziale, nelle entità del nostro simulatore, `"0"` dato che tutte le entità del simulatore sono mappate con interi 👍
