### ISSUE TITLE
Creare Astrazione richiesta 

### ISSUE THREAD

**Issue by Gianlo98** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#2]
Implementare la seguente astrazione di una richiesta

![immagine](https://user-images.githubusercontent.com/7064130/73071498-2d66c780-3eb3-11ea-9401-133b59402f21.png)

il metodo `executeRequest()` chiama il metodo `evaluateRequest(Request r)` della classe SEC passando se stesso come parametro

**Comment by ChrisTasca1997** [comment]
Per quanto riguarda executeRequest l'ho implementato, non capisco però cosa deve fare addAction(che nella nuova implementazione è addStatus).

**Comment by Gianlo98** [comment]
Nulla, è un refuso di una precedente modellazione 😬

**Comment by ChrisTasca1997** [comment]
> Nulla, è un refuso di una precedente modellazione 😬

Perfetto, allora dopo/domani mattina, ricontrollo e poi faccio una pullrequest(cercando di fare una merge prima, per evitare problemi)
