### ISSUE TITLE
Completare Inizializzazione Sistema

### ISSUE THREAD

**Issue by Gianlo98** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#3]
Verificare che la classe `SystemInitializer `sia in grado di

- [x] Istanziare correttamente le entità, registrando ogni nuova entita con il metodo `registerEntity(Entity e)` di EntityManager
- [x] Istanziare correttamente le automazioni e registrarle tutte nel sec con il metodo `registerAutomation(Request r)`

**Comment by ChrisTasca1997** [comment]
Rimango in attesa del metodo registerAutomation(Request r). Procedo con gli altri task.
