### ISSUE TITLE
Migliorare la Command Line Interface

### ISSUE THREAD

**Issue by Gianlo98** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#4]
Modificare la classe `CLIService` aggiungendo le seguenti funzionalità:

- [x] Accettare un comando `list` per la visualizzazione della lista di tutte le entità (`entityManager.getEntityMap()` ritorna una mappa <Integer, Entity> che associa ad ogni id una entità)
- [x] Accettare un comando `set <entity> <value> <retain_flag> <retain_level>` che crea una Richiesta con i valori passati in precedenza (`retain_flag `e `retain_level `opzionali, di default `retain_flag = false` e `retain_level = Integer.MAX_INT`)
- [x] Accettare un comando `get <entity>` che ritorni lo stato dell'entita (lo stato lo prendi da `entityManager.getEntityState()`)

Se necessario si usino classi di supporto a `CLIService`, **il cui scopo è solo quello di fare operazioni di I/O nella console**

**Comment by Gianlo98** [comment]
Il metodo `entityManager.getEntityMap()` devo ancora implementarlo perciò aspetta prima di andare avanti

**Comment by ChrisTasca1997** [comment]
Retain_level, lo chiamo priority, cosi come in SystemInit, va bene?

**Comment by ChrisTasca1997** [comment]
inoltre, mi sono accorto che per il task 1, per prendere i valori di entity, ho usato direttamente la classe Entity, mentre abbiamo detto che tutto deve passare per entityManager, quindi credo dei metodi in entityManager per ricavare i vari attributi di Entity?

**Comment by Gianlo98** [comment]
> 
> 
> Retain_level, lo chiamo priority, cosi come in SystemInit, va bene?

Perfetto

**Comment by Gianlo98** [comment]
> 
> 
> inoltre, mi sono accorto che per il task 1, per prendere i valori di entity, ho usato direttamente la classe Entity, mentre abbiamo detto che tutto deve passare per entityManager, quindi credo dei metodi in entityManager per ricavare i vari attributi di Entity oppure facciamo visualizzare solo lo stato?

Si è un'ottima osservazione, ci ho pensato pure io però al momento ti passo una lista che è una copia di quella originale (così se modifichi i valori delle entity non succede nulla). Più avanti cercheremo un'implementazione migliore, questa credo sia la più veloce ;D

**Comment by ChrisTasca1997** [comment]
Nel task 2 e 3 <entity> si riferisce all'id giusto?

**Comment by ChrisTasca1997** [comment]
Quando il comando è set, ho impostato a null il valore della richiesta, infatti non deve essere solamente eseguita.

**Comment by Gianlo98** [comment]
> Nel task 2 e 3 si riferisce all'id giusto?

Assolutamente si giustissimo

**Comment by Gianlo98** [comment]
> Quando il comando è set, ho impostato a null il valore dell'array Conditions, infatti deve essere solamente eseguita e non valutata.

Si va benissimo!

**Comment by Gianlo98** [comment]
Potresti mettere che se non specificate retain di default è false e priority è Integer.MAX_INT così fare i comandi set è meno verboso 😁

**Comment by ChrisTasca1997** [comment]
> Potresti mettere che se non specificate retain di default è false e priority è Integer.MAX_INT così fare i comandi set è meno verboso 😁

Si, ho già pensato a ciò, grazie 😊
