### ISSUE TITLE
Implementazione Observer

### ISSUE THREAD

**Issue by Gianlo98** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#6]
Ho un dubbio su una cosa: nell'interfaccia `Subject ` non appena un observer chiama l'attach/detach, il subject lo notifica chiamando il metodo `updateAdd()`/`updateRemove()`.  Il codice di cui parlo è questo: 

```
	public default void attach(Observer o) {
		observers.add(o);
		this.notifyAdd(o);
	}
	
	public default boolean detach(Observer o) {
		boolean a = observers.remove(o);
		o.updateRemove(this);
		return a;
	}
```

Questi metodi servono all'observer per fargli tenere traccia di una lista di classi a cui esso risulta sottoscritto
```
public interface Observer {
	public HashMap<Integer, Subject> subjects = new HashMap<Integer, Subject>();

	public default void updateAdd(Subject subject) {
		subjects.put(subject.hashCode(), subject);
	}

	public default void updateRemove(Subject subject) {
		subjects.remove(subject.hashCode(), subject);
	}

}

```

non capisco che utilità ha l'observer ad avere questa mappa in quanto la comunicazione è solo da subject ad observer e non viceversa.
![immagine](https://user-images.githubusercontent.com/7064130/73082126-25b21d80-3ec9-11ea-97f1-d7264a7ae75a.png)

**Comment by D-Mex** [comment]
Risale alla prima bozza di modellazione, lo aggiorno
