### ISSUE TITLE
Considerare di rinominare EntityAction

### ISSUE THREAD

**Issue by Gianlo98** [UnimibSoftEngCourse1920/progetto-smarthome-1-gruppo-smarthome-1#7]
La classe `EntityAction` rappresenta un'azione di un'entità. 
Dato che in tutto il sistema girano "messaggi" che hanno come oggetto principalmente `entity_id` e `status` propongo di rinominare la classe `EntityAction `in `EntityStatus` così da poterla usare in più contesti (update observer ad esempio).
Che ne pensate?

**Comment by ChrisTasca1997** [comment]
Si, non penso ci siano problemi, anche perché è più comprensibile a livello di logica del programma.

**Comment by ChrisTasca1997** [comment]
Ho rinominato la classe.

**Comment by Gianlo98** [comment]
Ho visto, ottimo!
Sempre per essere più coerenti con la logica del programma ho fatto anche queste 2 modifiche: 

1. il package `com.unimib.smarthome.command` -> `com.unimib.smarthome.request`. Questo package non contiene dei comandi, contiene tutto il necessario per creare una richiesta (che la si può vedere come un insieme di azioni/comandi)
2 nella classe `Request` il campo `retain_level` -> `priority`. E' più corretto definire un campo con il nome priorità invece che retain level perchè essa va guardata non solo quando la richiesta è retain ma anche quando non lo è. 

Se qualche modifica di queste non vi piace ditemelo che ne discutiamo, sono aperto a suggerimenti per trovare i nomi migliori!
